# TravisCI is testing manylinux1 wheels only.
# Azure is used to test the Anaconda compiler toolchina.
#
# Reference:
# - https://github.com/pypa/python-manylinux-demo

sudo: required
services:
  - docker

matrix:
  include:
    - env: PYVER=cp27-cp27mu ARCH=x64
    - env: PYVER=cp35-cp35m  ARCH=x64
    - env: PYVER=cp36-cp36m  ARCH=x64
    - env: PYVER=cp37-cp37m  ARCH=x64
    - env: PYVER=cp27-cp27mu ARCH=x32
    - env: PYVER=cp35-cp35m  ARCH=x32
    - env: PYVER=cp36-cp36m  ARCH=x32
    - env: PYVER=cp37-cp37m  ARCH=x32
    - arch: arm64
      env: PYVER=cp37-cp37m  ARCH=aarch64


install:
    - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
        DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64;
      elif [ "$ARCH" == "x64" ]; then 
        DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64; 
      else 
        DOCKER_IMAGE=quay.io/pypa/manylinux2014_i686; 
      fi
    - docker pull $DOCKER_IMAGE

script:
    - if [[ "${TRAVIS_CPU_ARCH}" == "arm64" ]]; then
         bash ./buildscripts/manylinux1/docker_run_$ARCH.sh build_llvmlite.sh $PYVER;
      else 
         ./buildscripts/manylinux1/docker_run_$ARCH.sh build_llvmlite.sh $PYVER;
      fi
notifications:
    email: false
    on_success: "change"
    on_failure: "always" # "change"
    slack:
        secure: "FKl89SqORRj0CQCeZZ6vLzSyX8644b+c3VMO2lfTMDj5asnSYmq4J8cmytzLuTO4vCDXXNzqbO+8jCsPtnt+2gvXC+NccZOvlPsHXOy9Iu4SAfPKmN2rsxlu27Tn86HN5zgGJsm53aQFG2BXnsc848/HtSzzxdUx8oml6w3SdwI="
